apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dk6ar9kug-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dk6ar9kug-nodejs 
  name: dk6ar9kug-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: dk6ar9kug-nodejs 
